import type { World } from "./types";

export const WORLDS: World[] = [
  {
    id: "golden-desert",
    name: "Golden Desert",
    subtitle: "Endless dunes beneath a low amber sun",
    terrain: "dunes",
    fogDensity: 0.0042,
    sunPosition: [-420, 80, -700],
    sunSize: 60,
    bloom: 0.9,
    ambientIntensity: 0.55,
    lightIntensity: 1.4,
    colors: {
      skyTop: "#f0b46a",
      skyBottom: "#c0512f",
      fog: "#d9824a",
      sun: "#fff2c4",
      sunGlow: "#ffd590",
      ground: "#d98b4a",
      groundDeep: "#9c4f28",
      structure: "#7a4326",
      structureGlow: "#ffcaa0",
      particle: "#ffd9a0",
      ambient: "#8a4a30",
      light: "#ffd6a0",
      banner: "#b8472e",
      auroraA: "#ffb070",
      auroraB: "#ff7a4a",
    },
    features: {
      aurora: false,
      stars: false,
      clouds: false,
      islands: false,
      water: false,
      embers: true,
      snow: false,
    },
  },
  {
    id: "moon-ocean",
    name: "Moon Ocean",
    subtitle: "Silver water mirrored under a vast night",
    terrain: "water",
    fogDensity: 0.0036,
    sunPosition: [380, 200, -600],
    sunSize: 44,
    bloom: 1.05,
    ambientIntensity: 0.4,
    lightIntensity: 0.9,
    colors: {
      skyTop: "#070e22",
      skyBottom: "#16294f",
      fog: "#16294f",
      sun: "#eaf1ff",
      sunGlow: "#bcd2ff",
      ground: "#0e1c3a",
      groundDeep: "#060d1f",
      structure: "#5d6e94",
      structureGlow: "#cfe0ff",
      particle: "#cfe0ff",
      ambient: "#1a2a4f",
      light: "#bcd2ff",
      banner: "#33507f",
      auroraA: "#6fd0ff",
      auroraB: "#9f8cff",
    },
    features: {
      aurora: false,
      stars: true,
      clouds: false,
      islands: false,
      water: true,
      embers: false,
      snow: false,
    },
  },
  {
    id: "ancient-kingdom",
    name: "Ancient Kingdom",
    subtitle: "Golden ruins adrift in a sea of cloud",
    terrain: "plains",
    fogDensity: 0.0052,
    sunPosition: [200, 240, -560],
    sunSize: 54,
    bloom: 1.1,
    ambientIntensity: 0.7,
    lightIntensity: 1.3,
    colors: {
      skyTop: "#a9d4f5",
      skyBottom: "#fdeec6",
      fog: "#f0e3c2",
      sun: "#fff7df",
      sunGlow: "#ffeab0",
      ground: "#ece1c6",
      groundDeep: "#cdbd97",
      structure: "#d8c089",
      structureGlow: "#fff0bd",
      particle: "#ffe9b0",
      ambient: "#cdbf9b",
      light: "#fff1cf",
      banner: "#c89a4c",
      auroraA: "#ffe0a0",
      auroraB: "#ffd070",
    },
    features: {
      aurora: false,
      stars: false,
      clouds: true,
      islands: true,
      water: false,
      embers: false,
      snow: false,
    },
  },
  {
    id: "emerald-valley",
    name: "Emerald Valley",
    subtitle: "Rolling green hills wrapped in morning mist",
    terrain: "hills",
    fogDensity: 0.0072,
    sunPosition: [-260, 150, -540],
    sunSize: 46,
    bloom: 0.8,
    ambientIntensity: 0.62,
    lightIntensity: 1.15,
    colors: {
      skyTop: "#bfe7d8",
      skyBottom: "#8fcdb6",
      fog: "#b7e0cf",
      sun: "#f1fff4",
      sunGlow: "#d8f5dd",
      ground: "#4f8f63",
      groundDeep: "#2c5740",
      structure: "#5f7d68",
      structureGlow: "#d6ffe0",
      particle: "#e6ffe9",
      ambient: "#3c6850",
      light: "#e6fff0",
      banner: "#3f7a55",
      auroraA: "#a0ffc8",
      auroraB: "#7fe0b0",
    },
    features: {
      aurora: false,
      stars: false,
      clouds: true,
      islands: false,
      water: false,
      embers: false,
      snow: false,
    },
  },
  {
    id: "snow-sanctuary",
    name: "Snow Sanctuary",
    subtitle: "Quiet snowfields under a waking aurora",
    terrain: "snow",
    fogDensity: 0.005,
    sunPosition: [300, 170, -640],
    sunSize: 40,
    bloom: 1.0,
    ambientIntensity: 0.55,
    lightIntensity: 1.0,
    colors: {
      skyTop: "#0e1d40",
      skyBottom: "#39598a",
      fog: "#9fb6d6",
      sun: "#eef5ff",
      sunGlow: "#cfe0ff",
      ground: "#dfe9f5",
      groundDeep: "#9fb4cf",
      structure: "#b6cce4",
      structureGlow: "#e8f3ff",
      particle: "#ffffff",
      ambient: "#3a567f",
      light: "#dce8ff",
      banner: "#6f8fc0",
      auroraA: "#7dffd0",
      auroraB: "#6fb6ff",
    },
    features: {
      aurora: true,
      stars: true,
      clouds: false,
      islands: false,
      water: false,
      embers: false,
      snow: true,
    },
  },
  {
    id: "dream-night",
    name: "Dream Night",
    subtitle: "A violet dusk where the stars come close",
    terrain: "dunes",
    fogDensity: 0.0044,
    sunPosition: [-340, 140, -660],
    sunSize: 38,
    bloom: 1.15,
    ambientIntensity: 0.48,
    lightIntensity: 0.85,
    colors: {
      skyTop: "#120a2e",
      skyBottom: "#2c1a55",
      fog: "#241046",
      sun: "#d6c2ff",
      sunGlow: "#b79bff",
      ground: "#281b48",
      groundDeep: "#160d2c",
      structure: "#5c3fa0",
      structureGlow: "#cab4ff",
      particle: "#d9c6ff",
      ambient: "#2a1a54",
      light: "#c4b0ff",
      banner: "#5a3fa0",
      auroraA: "#b48cff",
      auroraB: "#7a6cff",
    },
    features: {
      aurora: true,
      stars: true,
      clouds: false,
      islands: true,
      water: false,
      embers: false,
      snow: false,
    },
  },
];

export function getWorld(id: string): World {
  return WORLDS.find((w) => w.id === id) ?? WORLDS[0];
}
