import type { World } from "./types";

export const WORLDS: World[] = [
  {
    id: "savana-valley",
    name: "Savana Valley",
    subtitle: "A lush valley of golden grass, floating lands, and quiet rivers",
    terrain: "plains",
    fogDensity: 0.0048,
    sunPosition: [300, 200, -600],
    sunSize: 52,
    bloom: 0.95,
    ambientIntensity: 0.58,
    lightIntensity: 1.25,
    colors: {
      skyTop: "#5bbce3",
      skyBottom: "#d0ecd4",
      fog: "#cbead1",
      sun: "#fffef5",
      sunGlow: "#ffe699",
      ground: "#6ab879",
      groundDeep: "#255938",
      structure: "#4e321e",
      structureGlow: "#ffe9ad",
      particle: "#ffe9ad",
      ambient: "#365640",
      light: "#fff7dd",
      banner: "#d6533c",
      auroraA: "#60dfaa",
      auroraB: "#c5e884",
    },
    features: {
      aurora: true,
      stars: true,
      clouds: true,
      islands: true,
      water: true,
      embers: true,
      snow: false,
    },
  },
  {
    id: "midnight-ocean",
    name: "Midnight Ocean",
    subtitle: "A vast dark sea beneath a sky of stars and shifting light",
    terrain: "water",
    fogDensity: 0.0055,
    sunPosition: [-200, 80, -800],
    sunSize: 38,
    bloom: 1.1,
    ambientIntensity: 0.38,
    lightIntensity: 0.85,
    colors: {
      skyTop: "#0a0f2e",
      skyBottom: "#112244",
      fog: "#1a2a44",
      sun: "#b8d8ff",
      sunGlow: "#6099ff",
      ground: "#0d2040",
      groundDeep: "#060e20",
      structure: "#1a2e50",
      structureGlow: "#3a7aff",
      particle: "#88bbff",
      ambient: "#0a1530",
      light: "#c4d8ff",
      banner: "#2244aa",
      auroraA: "#4488ff",
      auroraB: "#88ffee",
    },
    features: {
      aurora: true,
      stars: true,
      clouds: false,
      islands: false,
      water: true,
      embers: false,
      snow: false,
    },
  },
  {
    id: "eternal-winter",
    name: "Eternal Winter",
    subtitle: "A frozen expanse where silence has weight and stars are close",
    terrain: "snow",
    fogDensity: 0.0062,
    sunPosition: [100, 60, -700],
    sunSize: 44,
    bloom: 0.9,
    ambientIntensity: 0.44,
    lightIntensity: 1.0,
    colors: {
      skyTop: "#1e2a3e",
      skyBottom: "#3a4f6e",
      fog: "#4a6070",
      sun: "#e8f0ff",
      sunGlow: "#a0c0ff",
      ground: "#c8d8e8",
      groundDeep: "#88a0b8",
      structure: "#8899aa",
      structureGlow: "#aaccff",
      particle: "#d8eeff",
      ambient: "#243040",
      light: "#d8ecff",
      banner: "#4466aa",
      auroraA: "#00ddaa",
      auroraB: "#5599ff",
    },
    features: {
      aurora: true,
      stars: true,
      clouds: true,
      islands: false,
      water: false,
      embers: false,
      snow: true,
    },
  },
  {
    id: "golden-sunrise",
    name: "Golden Sunrise",
    subtitle: "The moment dawn breaks and the world holds its breath",
    terrain: "hills",
    fogDensity: 0.0038,
    sunPosition: [50, 100, -700],
    sunSize: 72,
    bloom: 1.3,
    ambientIntensity: 0.65,
    lightIntensity: 1.45,
    colors: {
      skyTop: "#c85a20",
      skyBottom: "#f5c06a",
      fog: "#f0d0a0",
      sun: "#fff8e8",
      sunGlow: "#ffaa44",
      ground: "#8a6030",
      groundDeep: "#3a2010",
      structure: "#6a4020",
      structureGlow: "#ffd080",
      particle: "#ffcc66",
      ambient: "#503020",
      light: "#ffeecc",
      banner: "#cc6622",
      auroraA: "#ff8833",
      auroraB: "#ffdd88",
    },
    features: {
      aurora: false,
      stars: false,
      clouds: true,
      islands: true,
      water: false,
      embers: true,
      snow: false,
    },
  },
  {
    id: "crimson-dusk",
    name: "Crimson Dusk",
    subtitle: "A land of volcanic rock and fire where the sky bleeds red",
    terrain: "dunes",
    fogDensity: 0.0052,
    sunPosition: [500, 100, -500],
    sunSize: 64,
    bloom: 1.2,
    ambientIntensity: 0.52,
    lightIntensity: 1.35,
    colors: {
      skyTop: "#3a0820",
      skyBottom: "#cc3322",
      fog: "#883322",
      sun: "#fff0e0",
      sunGlow: "#ff6633",
      ground: "#4a2010",
      groundDeep: "#220a00",
      structure: "#3a1808",
      structureGlow: "#ff6622",
      particle: "#ff8844",
      ambient: "#2a0a00",
      light: "#ffd0a0",
      banner: "#cc2200",
      auroraA: "#ff4400",
      auroraB: "#ffaa22",
    },
    features: {
      aurora: false,
      stars: false,
      clouds: false,
      islands: false,
      water: false,
      embers: true,
      snow: false,
    },
  },
  {
    id: "mystic-valley",
    name: "Mystic Valley",
    subtitle: "Ancient forests and still water, where time moves differently",
    terrain: "plains",
    fogDensity: 0.006,
    sunPosition: [200, 160, -500],
    sunSize: 46,
    bloom: 0.85,
    ambientIntensity: 0.5,
    lightIntensity: 1.1,
    colors: {
      skyTop: "#1a3028",
      skyBottom: "#2a4838",
      fog: "#304838",
      sun: "#f0ffe8",
      sunGlow: "#88ffaa",
      ground: "#2a5030",
      groundDeep: "#0f2018",
      structure: "#2e4428",
      structureGlow: "#88ffcc",
      particle: "#aaffcc",
      ambient: "#182818",
      light: "#ddffe8",
      banner: "#225530",
      auroraA: "#22ffaa",
      auroraB: "#88ff66",
    },
    features: {
      aurora: true,
      stars: true,
      clouds: true,
      islands: false,
      water: true,
      embers: false,
      snow: false,
    },
  },
];

export function getWorld(id: string): World {
  return WORLDS.find((w) => w.id === id) ?? WORLDS[0];
}
